# http://www.practicepython.org/exercise/2014/07/05/18-cows-and-bulls.html

"""
Create a program that will play the 'cows and bulls' game with the user.
The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
For every digit that the user guessed correctly in the correct place,
they have a 'cow'.
For every digit the user guessed correctly in the wrong place is a 'bull'.
Every time the user makes a guess, tell them how many 'cows' and 'bulls'
they have. Once the user guesses the correct number, the game is over.
Keep track of the number of guesses the user makes throughout the game and
tell the user at the end.

Say the number generated by the computer is 1038.
An example interaction could look like this:

Welcome to the Cows and Bulls Game!
  Enter a number:
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
"""

from random import randint

print "Welcome to the Cows and Bulls Game!"

number = "".join(["1234567890"[randint(0, 9)] for i in range(4)])
print number

def check(input_, number):
  cows = 0
  bulls = 0
  for i in range(len(number)):
    if input_[i] == number[i]:
      cows += 1
    elif input_[i] in number: # something doesn't seem right
      bulls += 1
  if cows == 4:
    return "0"
  else:
    res = str(cows) + " cow, " if cows <= 1 else str(cows) + " cows, "
    res += str(bulls) + " bull" if bulls <= 1 else str(bulls) + " bulls"
    return res

trials = 0
while True:
  trials += 1
  input_ = raw_input("Enter a number: ")
  if len(input_) != 4:
    print "Please enter a 4 digit number."
  else:
    result = check(input_, number)
    if result == "0":
      print "You have guessed the number with a total of " + str(trials) + " guesses!"
      break
    else:
      print result
